theme: minima
title: My first blog (I'm shure it's a very original title)
author: Eugene
email: my-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My first try.

# social links
twitter_username: my-twitter-handle
github_username:  my-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
